# Responsibilties 

TA responsibilities will vary between classes therefore TAs should obtain from the instructor clear guidelines for the specific tasks required of the TA. Many of these tasks are described in general terms below.

- Most TA lab duties this semester are likely to be in person while other duties may be remote. Your office hours and duties will need to accommodate changes in University policies as the semester proceeds.  We are asking that all courses set up at least some Zoom office hours to accommodate students who are ill or in isolation or stuck traveling. 

- In general, we request that TAs working 8-15 hours per week hold two hours of office hours each week and those working less hold one hour. Your instructor may have different requirements. 

- We prefer that all TAs holding office hours make at least one of those hours in Zoom each week. TAs who prefer to conduct all of their office hours remotely are welcome to do so.

- Please keep informed of the latest Duke policies at [keeplearning.duke.edu](https://keeplearning.duke.edu/), [keepworking.duke.edu](https://keepworking.duke.edu/), and [coronavirus.duke.edu](https://coronavirus.duke.edu/).

- Answer all communications from the department, your instructor, other campus employers, and the university, within 24 hours, before the end of the next business day.

- If you miss a scheduled meeting, training, office hours or other event, immediately contact the instructor. 

- Complete all requested training and learn the technology tools required for the course you are assisting. 

- Get in touch with the instructor before the first class and be available to meet with the instructor during the first week of class. 

- If you are assigned the duties of a lead TA, meet with your instructor and make sure you understand what is expected of you for that role in that course.

- Attend regular meetings with the instructor (typically at least once a week). 

- Attend the first live or online class session (if possible and requested to do so) and discuss with the instructor whether continued attendance is required. For TAs new to a course or the TA experience, attendance throughout the semester is often expected. Ask your instructor about their policy.

- Assist in assessing and reporting student performance to the instructor. This includes identifying top and/or struggling students and identifying problems or concepts causing difficulty for students. YOUR FEEDBACK IS CRUCIAL TO US!  

- Respond to students' e-mails, forwarding common questions to the instructor and other TAs (if any). Your instructor will set expectations about the format students will use to answer questions. If the instructor is using Ed Discussion, Sakai Conversations, or another tool for Q&A, discuss with the instructor expectations about answers and about how to handle getting students to ask their questions in that tool rather than in emails. You may be asked to cover answering questions on particular days. 

- Office hours will be held in some combination of in person and online sessions for each course. We prefer that evening office hours be held online or in a more public place, such as the library, than in Old Chemistry at night. Be accessible in a reliable manner by working out the schedule of your office hours with the instructor, announcing and then holding your regular office hours. Your primary duty during the office hours is to help students from your course. See below for general guidelines for office hours. 

- Your other duties and responsibilities might include but are not limited to:
  - Grade labs, homework assignments, exams, etc. using Gradescope and other tools.
  - If the course has a lab component, review to prepare and then run labs or assist in labs. 
  - Conduct review sessions prior to exams, if the instructor requests.
  - Help maintain the course website or Sakai site.
  - Work with student teams on their group projects.
  - Improve your teaching skills by training, practice,  observations and feedback.

- Keep accurate track of time spent on the course and report to the instructor if your hours are above or below the expected level. 

- If you are paid biweekly, update and save your timecard when you finish work for the day and submit promptly before the deadline. 

- Stay available for synchronous course related duties until the end of the final exam week.
  - **The academic calendar for Spring 2022 can be found here: https://registrar.duke.edu/spring-2022-academic-calendar**
  - **Fall final exams end at 10 pm on Saturday, April 30	. Specific final exam schedules are available at Exam schedules for https://registrar.duke.edu/calendars-key-dates/exam-schedules.** Grades are due within 48 hours of the end of the exam period. This means TAs for are expected to continue to hold office hours during their respective final exam periods, and to be available for grading final exams in their assigned courses unless they make special arrangements with the course instructor. Please discuss the end of semester plans with the instructor you are assisting right away. 

- **Always complete the course and TA evaluations in the courses for which you are enrolled as a student.**
