---
title: "Guidelines"
---

## Before Classes Begin

-   Trinity resources: The undergraduate bulletin (<https://registrar.duke.edu/university-bulletins/undergraduate-instruction>) and T-Reqs (Trinity Requirements) (<https://trinity.duke.edu/undergraduate/academic-policies> are sources for Trinity College Academic Policies and Procedures. You are encouraged to review this site for information on university policy on religious holidays, disability accommodations, class attendance, credits, exams and grading, harassment, plagiarism, etc. For graduate courses, use the Graduate Bulletin <https://registrar.duke.edu/university-bulletins/graduate-school> and the Graduate School's policy site <https://gradschool.duke.edu/academics/academic-policies>.

-   Technology: During training, you will be asked about your ability to use Gradescope for grading and Zoom and whiteboarding for online meetings.
    It's fine to use a do-it-yourself hack to turn your cell phone into a document camera aimed at paper or a whiteboard.
    If needed for a particular course or online office hours, let us know if you lack a tablet and stylus or something to use for written explanations; it is possible to acquire an inexpensive drawing device if you need one for whiteboarding.
    Also let us know your WiFi situation.
    Talk with your instructor and Dr. Durso.

-   Books: Many courses now have electronic versions of the text available for free online or through the Duke Libraries.
    Please check with your instructor first.
    For some courses, the Assistant to the DUS Mrs. Karen Whitesell (karen.whitesell\@duke.edu) has physical desk copies of most books that you may use for TAing the course, but you must return the book at the end of the semester.
    Please contact her if you need a textbook copy for the course.

-   Course website: Familiarize yourself with the website for the course.
    This may be a site designed by the instructor or it may be a Sakai site.
    Sakai is a university wide course development and presentation platform; all courses use Sakai at least for grades.
    You will need a NetID to access Sakai at http://sakai.duke.edu.
    It allows faculty (and TAs if the faculty gives permission) to post course information such as lecture notes, assignments, announcements, exam solutions, and other teaching materials to which you want your students to have access.
    It also will also allow you to send emails to individuals or groups, host online discussions, collect homework assignments, and allow students to view their grades.
    For an overview of capabilities and various tutorials go to http://support.sakai.duke.edu/sakai-basics.
    Your TA training may include Sakai training as well.
    If you have problems with Sakai, let your instructor know.
    Note that undergraduate TAs are not supposed to have access to the full gradebook in Sakai; however, you may be able to do anonymous grading.
    Sakai is also able to organize Zoom meetings for the course lectures, labs, and office hours.
    Check with your instructor or Dr. Durso.
    Learning Innovation also offers training on Sakai.

-   Discussion tools: Piazza is no longer supported by Duke University but individual instructors may still choose to use it.
    Alternative discussion tools include Conversations in Sakai, and other tools your instructors may choose.
    Once your instructor has chosen which tool they will use, ask for training on that tool.

-   Gradescope: Gradescope is an online grading tool that is usually integrated with Sakai.
    Gradescope is used extensively in the department and all TAs will be trained on its use.
    If your instructor is using it, they will explain what they expect.
    If you have never used it, be sure to ask any questions you have so that you fully understand how to grade in Gradescope.
    You will access Gradescope using your NetID similarly to accessing Sakai.
    If you have previously used Gradescope for grading and think it would assist in your course duties this semester, discuss this with your instructor.
    If you or the instructor would like help with Gradescope, ask Joan Combs Durso, the Coordinator of Undergraduate Training, Research, and Development.
    We have a training site set up and TAs will provide sample documents for grading training.
    The workflow for syncing grades from Gradescope to Sakai has changed this semester.
    Training will be offered if needed.

-   Copies: Copy procedures are changing.
    If your instructor asks you to make physical copies for the course, please contact Mrs. Whitesell and cc: Dr. Durso on the email.
    We'll get you access and instructions.

-   Supplies: Please let your instructor know if you have any unmet supply needs such as chalk, dry-erase markers, red pens, etc.
    These are only for instructional and grading purposes, not for your personal use.
    If these items are missing in a TA office hours space, please let Mrs. Whitesell and Dr. Durso know.

-   Computing labs: Most introductory undergraduate labs in StatSci are bring-your-own-device labs.
    Large introductory classes often use OIT provided Docker containers for computing.
    Graduate courses often use department servers.
    In remote teaching, the situation is complicated by distance and the need to see the screen of your students.
    Graduate Teaching Assistants and experienced undergraduates usually supervise the computing lab sections.
    Get help with the computing environment from Dr. Durso or from Learning Innovation's online training options.

-   Collaboration Tools: Whether your instructor is using email, Slack, Basecamp, Microsoft Teams, or any other collaboration tool, make sure you understand how to use it and what your instructor's preferred communication methods are.

## Professionalism

-   Whether you are attending a live class session with the instructor, leading a lab, or holding office hours online, please recall that you are a leader of students and representing the department.
    Students may show up to online sessions in pajamas, wrapped in blankets, and attending their session from their beds, but the TA shouldn't.
    If students show up inappropriately dressed, please discuss the issue with the instructor.

-   Use an appropriate virtual background if needed and if your computer can handle it.
    Try to be in a boring environment, not in a distracting one.
    A bookcase or office space, a living room or even a yard are fine backgrounds.
    Be sure to have adequate lighting.
    Sometimes it is just a matter of turning to face a different direction.
    No need to buy a ring light, but there are many YouTube videos that show you how to set up a good environment for leading an online session.

-   For online sessions, if your environment is noisy, use a headset and mute yourself when you are not speaking.
    Practice in advance where you know you will be, so you can have someone listen to you and make sure the sound is adequate.

-   If you need help with this, please contact Dr. Durso.

## Labs

-   Meet with the course instructor before courses begin and at least once a week during the semester to learn how the instructor would like the lab session run and to discuss upcoming labs and any issues that arise during the semester.
    First year graduate students have usually not learned about statistics from the same perspective as our undergrad courses, and some have never used the software that they will be teaching.
    Don't hesitate to ask questions.
    Undergraduates may have taken the course from a different instructor whose approach is different.
    Talk to the instructor of this course!

-   During the first day of lab, do what you can to set the climate of the course and develop a rapport with the class.
    Get students to interact with you and their classmates either through introductions, small group discussion, or asking questions.
    Give information about yourself that helps establish that you are both credible and approachable.
    You will want students to leave after the first class knowing why the lab sections are important and what your expectations will be.
    You will want to leave after the first class knowing the students' expectations and knowing that they are engaged enough to begin expending the time and energy needed to do well in the course.

-   Make sure you have worked through the lab ahead of time leaving plenty of time to ask the instructor for clarification.
    Make sure you understand the general learning objectives.
    Be ready to explain to students why they are being asked to do the exercise.

-   During lab, engage the students.
    Encourage them to explore and play rather than simply go through the motions.
    Ask them questions.
    Be receptive to their questions.
    Help them make the link between the computing lab and what has been covered in the text and lectures.

-   Check in with breakout groups online, even when it looks like there are no questions.
    Wander around the live classroom or lab.
    Students are more likely to reach out and ask a question if you're physically (or virtually) closer to them than if you're sitting in front of the classroom.
    Don't ask the Ferris Bueller query "Any questions?" Instead, "what questions do you have for me?" or "I'll take 3 questions now" are both better ways to solicit inquiry.

-   Please avoid *"didactic dictation"*.
    One of the most frustrating experiences for a new user of R is to have code quickly and sometimes inaudibly dictated to them by an experienced coder who talks too fast while typing in unreadably tiny font on a screen half the class can't see, and allows no time for correction, troubleshooting, or questions.
    Live coding, where you are demonstrating something as you talk about it, and students code along, should be done slowly.
    You don't have to be perfect.
    It's okay to make mistakes and correct them, modeling authentic coding for your students.
    Demonstrate first, and then have students work on their own code.
    Watch for frustration.
    Address it positively.

Excellent suggestions for how to do this well can be found [here](https://mine-cetinkaya-rundel.github.io/golive-uscots/golive.html#1).

-   If you have suggestions for improving the lab materials or find errors in the lab instructions, please discuss them with your instructor.

-   It may be a hardship for some students to have to use their cameras during an online lab session, but make sure to set expectations.
    You can't see how they are doing if their cameras off the whole session.
    Try at least starting with cameras on for a check-in.
    Talk with the instructor about setting expectations.
    Use activities to keep students engaged even if their cameras are not able to be used.

## Office Hours

-   Many instructors will set up Zoom office hours rooms in Sakai.
    Practices may differ between instructors but it is a good idea to set up a Google sheet that stays linked in Sakai that can be used for students to indicate their question or need.
    This will help you manage the crowd that could show up.
    You will find an example of this in the TA training site in Sakai.

-   Make sure you have read the text and class notes.
    Use the same notation, definitions, and perspectives as the author of the text and the instructor of the class.

-   Make sure to convey your interest in helping students.
    Sitting in the help room (or on Zoom) doing your own homework and not making eye contact with an entering student will often convey to the student that you are not interested in helping.

-   Avoid solving homework problems for students.
    Giving students the answer does not help them develop the problem-solving skills that will be necessary for them to do well in the course.
    Ask guiding, probing questions, but get the student to do the thinking.
    Offer similar problems as examples to work through, together.

-   Students differ in their mathematical preparation, and for our undergraduate courses, students will often be very rusty on algebra or calculus, depending on the course.
    Be sure to work from the level of the student.
    If a student is in trouble beyond your abilities, refer them to the instructor.

-   Make sure to speak clearly, slowly, and audibly, whether in person or online.
    Do not assume that your students knows a particular theorem or distribution if it has not yet been used in the course.
    Speak respectfully and let them know the course is meant to be challenging but success happens with practice and spending sufficient time on the work.

-   When you don't know how to work to the answer, do NOT fake it.
    Be honest, and seek another TA or the instructor.
    Giving a student incorrect information will snowball into a larger problem.
    If you promise to get back to them, write it down and follow it up.
    Share with your peer TAs or ask in a discussion forum in the TA training site.

-   Let the instructor know if you have students who are struggling with the material or who don't know where to begin.
    It's hard for anyone to ask for help if they are not used to needing it.
    Be kind and patient with students who show up feeling panicked or anxious.
    Reach out to Duke Reach if you suspect they need help, and let the instructor know.
    But mostly, be kind.
    You were a beginner once, and the student genuinely may be lost or have not learned how to study in an online course.
    Help them, and get help with this if it's a problem.
    Kindness and patience are the best compliments in TA evaluations.

## Grading

-   Set grading policies for partial credit, late papers, etc. with the instructor.
    Make sure these policies are easily accessible by students (e.g., on Sakai).
    Make sure you understand the instructor's expectations.

-   Find out from the instructor whether they expect you to make the solution key or grading rubric, including both answers and a breakdown of how points will be distributed.
    Ask the instructor to review before it goes live.

-   Before you begin to grade, go through solutions and double check answers, points, etc.

-   Grade by question, i.e., grade all of question 1, then all of question 2, etc. This will facilitate greater consistency.
    You may be assigned only one or a few questions from an entire assignment, especially if you are using Gradescope.

-   If you are sharing grading duties, make sure to calibrate for consistency.
    Students will be frustrated and angry if graders differ in their process of assigning points (and you will hear about it!).

-   Many courses use *positive grading* in the department.
    For each problem, clearly mark the number of points earned and the number of points possible.
    Gradescope or Sakai will do the tallying for you.

-   Record grades as per instructions of the instructor, but always double check your work.

-   Check with the instructor on how to enter missing grades, i.e. with a blank or a zero.
    Blanks can play havoc with scoring algorithms that require replacing minimums.
    This also depends on whether you are grading with Gradescope or Sakai.

-   Grading turnaround deadlines will be set by the instructor.
    Be sure you understand their expectations and that you communicate your time availability.
    Gradescope shows what you have already graded and haven't.
