project:
  type: book
  output-dir: docs

book:
  title: "Duke Statistical Science TA Manual"
  date: now
  reader-mode: true
  repo-url: https://github.com/DukeStatSci/ta-manual
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - useful-links.qmd
    - covid19.qmd
    - responsibilities.qmd
    - training.qmd
    - guidelines.qmd
    - students.qmd
    - evaluation-recognition.qmd

format: 
  pdf: default
  html: 
    mainfont: "Atkinson Hyperlegible"
    toc: true

editor: visual