project:
  type: book
  output-dir: docs

book:
  title: "Duke Statistical Science TA Manual"
  date: now
  reader-mode: true
  repo-url: https://github.com/DukeStatSci/ta-manual
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [pdf]
  chapters:
    - index.qmd
    - useful-links.qmd
    - responsibilities.qmd
    - best-practices.qmd
    - policies.qmd
    - resources.qmd
    - training.qmd
    - head-ta.qmd
    - evaluation-recognition.qmd
    - people.qmd

format: 
  pdf: default
  html: 
    mainfont: "Atkinson Hyperlegible"
    toc: true
    theme:
      light: [cosmo, style/style.scss]
      dark: [solar, style/style.scss, style/style-dark.scss]

editor: visual
