project:
  type: book

book:
  title: "Duke Statistical Science TA Manual"
  date: "29 August 2022"
  reader-mode: true
  repo-url: https://github.com/DukeStatSci/ta-manual
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - 01-useful-links.qmd
    - 02-covid19.qmd
    - 03-responsibilities.qmd
    - 04-training.qmd
    - 05-guidelines.qmd
    - 06-students.qmd

format: pdf

editor: visual