---
title: Evaluation and recognition
---

## Evaluation

Continuation of the opportunity to hold a Teaching Assistantship is contingent on good TA performance.
Student and faculty evaluations of TAs will occur at the end of each semester via surveys.
Excellent TA evaluations can also provide the basis for future recommendation letters from faculty.
TAs will be able to review their evaluations at the end of each semester.

We also recommend getting feedback from your students during the semester.
If your instructor does not do a midcourse survey for anonymous feedback from students and you wish to set up one for yourself, please contact Dr. Durso for help with a Qualtrics survey.

## Recognition

The Department of Statistical Science recognizes one doctoral student, one master's student and one undergraduate student as TAs of the Year each spring during commencement festivities.
Faculty members will be asked to nominate TAs for this award each semester (for TAs in Summer 2023, Fall 2023, and Spring 2024 courses) and a departmental committee will decide on the winners based on faculty and student evaluations.
TAs of the Year will be recognized at the departmental graduation at the end of the academic year.
These are cash awards and the amount are \$1,500 for PhD TAs, \$1,000 for MS TAs, and \$750 for undergraduate TAs.
