---
title: "Resources"
---

Familiarize yourself with resources available to your students for learning as well as mental health and wellness. And note that as students these resources may be available to you as well (some of them are undergraduate specific, some are open to all).

## Learning resources

**The Academic Resource Center:** (919) 684-5917, [theARC\@duke.edu](mailto:theARC@duke.edu), or [arc.duke.edu](https://arc.duke.edu/).

## Mental health and wellness

Our students can be under a lot of stress. Any lab absences, missed deadlines, or concerning behavior should be brought to your instructor's attention. In addition, familiarize yourself with mental health and wellness resources:

-   **The Academic Resource Center:** (919) 684-5917, [theARC\@duke.edu](mailto:theARC@duke.edu), or [arc.duke.edu](https://arc.duke.edu/).

-   **DuWell:** (919) 681-8421, provides Moments of Mindfulness (stress management and resilience building) and meditation programming to assist students in developing a daily emotional well-being practice. To see schedules for programs please see <https://students.duke.edu/wellness/duwell/>. All are welcome and no experience necessary.

-   **DukeReach:** Provides comprehensive outreach services to identify and support students in managing all aspects of well-being. If you have concerns about a student's behavior or health visit the website for resources and assistance: <https://students.duke.edu/wellness/dukereach/>.

-   **Counseling and Psychological Services (CAPS):** CAPS services include individual and group counseling services, psychiatric services, and workshops. To initiate services, walk-in/call-in 9-4 M,W,Th,F and 9-6 Tuesdays. CAPS also provides referral to off-campus resources for specialized care. (919) 660-1000 or [https://students.duke.edu/wellness/caps](https://students.duke.edu/wellness/caps/).

-   **TimelyCare:** (formerly known as Blue Devils Care) An online platform that is a convenient, confidential, and free way for Duke students to receive 24/7 mental health support through TalkNow and scheduled counseling: [https://bluedevilscare.duke.edu](https://bluedevilscare.duke.edu/). This link takes you to the TimelyCare site.

First year students and visiting students, in particular, may not be aware of these resources. Let the instructor know if you are concerned about a student's behavior or attendance or sudden changes in quality and timeliness of assignments. You can also let the Director of Undergraduate Studies or the Undergraduate Coordinator of your concerns. If you are holding office hours on nights or weekends, virtual campus resources may be more lightly staffed, so you should also know about other options for help.

In the event of an emergency requiring transportation, call 911. For non-emergencies, call campus police at (919) 684-2444.

Importantly, note that these resources are available to you as well. If you find yourself in distress, reach out to your course instructor, the DUS, or the Undergraduate Coordinator. Let us know immediately if you need help. We're here to help and always happy to talk!
