---
title: Responsibilities
---

Depending on your level (undergraduate, MS, or PhD student), the number of hours you're expected to work as a TA varies:

-   Undergraduate TAs are expected to work 8-10 hours per week, on average.

-   MS TAs are expected to work 12-15 hours per week, on average.[^1]

-   PhD students have a variety of assignments:

    -   Full TAs are expected to work 12-15 hours, on average.

    -   Half TAs or RA/TAs are expected to work 6-7.5 hours per week, on average.

    -   RA+s are expected to work 4-5 hours per week, on average.

[^1]: Unlike PhD TAs, we don't generally have part-time MS TAs since the funding structure for these two types of students is different.
    However, sometimes, we might need a specific MS TA for a particular MS course and might be able to negotiate a part-time offer for them upon their request.
    In these rare cases, being a 50% MS TA is possible, amounting to 6-7.5 hours per week.

Within these hours, TA responsibilities will vary between classes.
Therefore, TAs should obtain clear guidelines from the instructor for the specific tasks required of them.
Many of these tasks are described in general terms below.

-   Complete all training and learn the tools and technologies required for the course you are assisting.

-   Read and respond to all communication from the department, your instructor, other campus employers, and the university within 24 hours or before the end of the next business day, whichever is sooner.

-   Complete your profile in Canvas with a photo, phonetic name spelling, and other requested information in your TA Training site and TA course site.

-   Familiarize yourself with the university curricula and policies, including policies and procedures for religious holidays, disability accommodations, class attendance, credits, exams and grading, harassment, plagiarism, etc.:

    -   Undergraduate courses:

        -   Undergraduate bulletin, including T-Reqs (Trinity Requirements): <https://undergraduate.bulletins.duke.edu>

        -   Trinity College Academic Policies and Procedures: <https://trinity.duke.edu/undergraduate/academic-policies>

    -   Graduate courses:

        -   Graduate Bulletin: [https://graduateschool.bulletins.duke.edu](https://graduateschool.bulletins.duke.edu/){.uri}

        -   Graduate School Academic Policies and Procedures: <https://gradschool.duke.edu/academics/academic-policies>

-   Get in touch with the instructor before the first class and be available to meet with the instructor during the first week of class.

-   Attend regular meetings with the instructor, typically at least once a week.

-   Office hours:

    -   Office hours can be in person or remote. We strongly recommend that all courses set up at least some Zoom office hours to accommodate students who are ill in isolation or stuck traveling. Check with your course instructor for the ideal distribution of Zoom / in-person office hours.

    In general, TAs working 8-15 hours per week should have two office hours each week, and those working less should have one hour.
    However, your instructor may prefer a different distribution of responsibilities among their TAs.

    -   Your primary duty during office hours is to help students from your course.

-   Lectures: We strongly recommend all TAs attend the first lecture of the semester and discuss with the instructor whether continued attendance is required.
    For TAs new to a course or new to the TA role, attendance throughout the semester is a great way to stay connected and up-to-date with the course.
    Ultimately, though, your instructor will decide whether lecture attendance is required.
    Some or all TAs assigned to a course might be tasked with helping with active learning exercises during lectures.

-   Labs:

    -   Provide your availability to your course instructor for leading/helping out with labs as soon as possible after your TA assignment.

    Prepare for lab sessions by reviewing the lab assignment.
    This includes running through the assignment, running the code, and providing feedback to the instructor if anything is incorrect or unclear.

    -   Meet with your instructor and ensure you understand what is expected of you for that role in that course.

    -   In general, lab leaders should plan to spend the first 5-15 minutes of the lab session introducing the lab and setting the stage for the exercises students will work through during the session.
        For the remainder of the lab session, TAs are expected to walk around, answer questions, facilitate teamwork, etc.

-   If you are assigned the duties of a Head TA, see the [section on Head TAs](https://dukestatsci.github.io/ta-manual/head-ta.html).

-   Respond to students' e-mails, forwarding common questions to the instructor and other TAs (if any).
    Your instructor will set expectations about the format students will use to ask questions.
    If the instructor is using Ed Discussions or another tool for Q&A, discuss with the instructor expectations about answers and how to get students to ask questions in that tool rather than in emails.
    You may be asked to cover answering questions on particular days.

-   Monitoring performance / keeping the pulse of students' learning:

    -   Assist in assessing and reporting student performance to the instructor.
        This includes identifying top and struggling students and identifying problems or concepts causing difficulty for students.
        Your attention to student learning and your communication are crucial!

    -   Let the instructor, the Director of Undergraduate Studies, and/or the Undergraduate Coordinator know if you think a particular student needs support.

-   Your other duties and responsibilities might include but are not limited to:

    -   Grade labs, homework assignments, exams, etc., using Gradescope and other tools.
    -   If the course has a lab component, review to prepare, run, or assist in labs.
    -   Conduct review sessions before exams if the instructor requests them.
    -   Help maintain the course website or Canvas site.
    -   Work with student teams on their group projects.
    -   Improve your teaching skills by training, practice, observations, and feedback.

-   Stay available for course-related duties until the end of the final exam week.

    -   **Fall 2025 final exams end at 10 pm on Monday, December 15.** Grades are due within 48 hours of the end of the exam period. This means TAs are expected to continue holding office hours during their final exam periods and be available to grade final exams in their assigned courses unless they make special arrangements with the course instructor. Please discuss the end-of-semester plans with the instructor you are assisting right away.

-   If you miss a scheduled meeting, training, office hours, or other event, immediately contact the instructor.

-   Timekeeping:

    -   TAs are each issued an individual offer letter that spells out the terms and conditions, expected hours, and compensation for their service as a TA.
        Read the offer letter, ask any questions, and if there are no further questions, sign it and return it to the sender.

    -   Keep accurate track of time spent on the course and report to the instructor if your hours are consistently above or below the expected levels.

    -   Never exceed a total of 19.9 compensated hours per week across all campus duties.

    -   Inform the Business Manager right away if you have a Work Study Allocation that you plan to use in our department.

    If you are paid biweekly, update and save your time card when you finish work for the day and submit it promptly before the deadline.
    If you do not turn in your time card, you will not get paid for the hours you worked.
    Our Business Manager may send you a reminder or ask you questions about your time card, but it is ultimately your responsibility to turn in your hours.

-   Illness:

    -   If you become ill or have an emergency and cannot perform your assigned duties, please see to your immediate needs (<https://studentaffairs.duke.edu/studenthealth>). Then, let the instructor and the Undergraduate Coordinator know as soon as possible. Follow the guidelines found at <https://coronavirus.duke.edu>.
    -   If the instructor stops showing up, contact the DUS right away.
    -   If another TA or a student stops showing up, contact the instructor immediately.

-   Always complete the course and TA evaluations in the classes you are enrolled in.